[package]
name = "lm"
version = "0.1.0"
edition = "2021"
description = "A CLI and Rust library for controlling La Marzocco Home espresso machines"
authors = ["Tim Rogers"]
license = "MIT"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
dirs = "5.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.32", features = ["full"] }
