name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Run cargo check
      run: cargo check --verbose
      env:
        RUSTFLAGS: "-A dead_code"
      
    - name: Run cargo test
      run: cargo test --verbose
      env:
        RUSTFLAGS: "-A dead_code"
      
    - name: Run cargo clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      
    - name: Run cargo fmt check
      run: cargo fmt --all -- --check